export const ListOfOrchids = [
  {
    id: 1,
    name: "Taichung beauty",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/taichung_beauty.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: 2,
    name: "Blue Moon",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/blue_moon.jpg",
    color: "blue",
    origin: "Thailand",
    category: "Phalaenopsis",
  },
  {
    id: 3,
    name: "Golden Sun",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/golden_sun.jpg",
    color: "yellow",
    origin: "Vietnam",
    category: "Dendrobium",
  },
  {
    id: 4,
    name: "White Angel",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/white_angel.jpg",
    color: "white",
    origin: "Japan",
    category: "Phalaenopsis",
  },
  {
    id: 5,
    name: "Purple Queen",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/purple_queen.jpg",
    color: "purple",
    origin: "Thailand",
    category: "Vanda",
  },
  {
    id: 6,
    name: "Red Fire",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/red_fire.jpg",
    color: "red",
    origin: "China",
    category: "Cymbidium",
  },
  {
    id: 7,
    name: "Snow Fairy",
    rating: 3,
    isSpecial: false,
    image: "./src/assets/images/snow_fairy.jpg",
    color: "white",
    origin: "Korea",
    category: "Phalaenopsis",
  },
  {
    id: 8,
    name: "Pink Dream",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/pink_dream.jpg",
    color: "pink",
    origin: "Vietnam",
    category: "Cattleya",
  },
  {
    id: 9,
    name: "Green Forest",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/green_forest.jpg",
    color: "green",
    origin: "Malaysia",
    category: "Paphiopedilum",
  },
  {
    id: 10,
    name: "Sunset Glow",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/sunset_glow.jpg",
    color: "orange",
    origin: "Indonesia",
    category: "Oncidium",
  },
  {
    id: 11,
    name: "Night Star",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/night_star.jpg",
    color: "dark purple",
    origin: "Thailand",
    category: "Vanda",
  },
  {
    id: 12,
    name: "Morning Dew",
    rating: 3,
    isSpecial: false,
    image: "./src/assets/images/morning_dew.jpg",
    color: "light pink",
    origin: "Vietnam",
    category: "Dendrobium",
  },
  {
    id: 13,
    name: "Golden Star",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/golden_star.jpg",
    color: "yellow",
    origin: "Taiwan",
    category: "Phalaenopsis",
  },
  {
    id: 14,
    name: "Ocean Breeze",
    rating: 4,
    isSpecial: false,
    image: "./src/assets/images/ocean_breeze.jpg",
    color: "blue",
    origin: "Singapore",
    category: "Phalaenopsis",
  },
  {
    id: 15,
    name: "Royal Velvet",
    rating: 5,
    isSpecial: true,
    image: "./src/assets/images/royal_velvet.jpg",
    color: "violet",
    origin: "Thailand",
    category: "Cattleya",
  },
  {
    id: 16,
    name: "Spring Light",
    rating: 3,
    isSpecial: false,
    image: "./src/assets/images/spring_light.jpg",
    color: "soft pink",
    origin: "Vietnam",
    category: "Dendrobium",
  },
];
